// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPathsInWorkspace(arg1) {
  return window['go']['main']['App']['CheckPathsInWorkspace'](arg1);
}

export function CheckPermissions() {
  return window['go']['main']['App']['CheckPermissions']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function ExecutePicoclawCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecutePicoclawCommand'](arg1, arg2);
}

export function GetAIResponse(arg1, arg2) {
  return window['go']['main']['App']['GetAIResponse'](arg1, arg2);
}

export function GetChannelConfig() {
  return window['go']['main']['App']['GetChannelConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetPicoclawStatus() {
  return window['go']['main']['App']['GetPicoclawStatus']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function InstallSkill(arg1) {
  return window['go']['main']['App']['InstallSkill'](arg1);
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function Onboard(arg1) {
  return window['go']['main']['App']['Onboard'](arg1);
}

export function OpenLocalPath(arg1) {
  return window['go']['main']['App']['OpenLocalPath'](arg1);
}

export function OpenPermissionSettings(arg1) {
  return window['go']['main']['App']['OpenPermissionSettings'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RequestPathAuthorization(arg1) {
  return window['go']['main']['App']['RequestPathAuthorization'](arg1);
}

export function SaveChannelConfig(arg1) {
  return window['go']['main']['App']['SaveChannelConfig'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetCurrentSession(arg1) {
  return window['go']['main']['App']['SetCurrentSession'](arg1);
}
