// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWindow():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<main.ChatSession>;

export function DeleteSession(arg1:string):Promise<void>;

export function ExecutePicoclawCommand(arg1:string,arg2:Array<string>):Promise<string>;

export function GetAIResponse(arg1:string):Promise<main.ChatSession>;

export function GetConfig():Promise<main.Config>;

export function GetCurrentSession():Promise<main.ChatSession>;

export function GetPicoclawStatus():Promise<Record<string, any>>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function GetSession(arg1:string):Promise<main.ChatSession>;

export function GetSessions():Promise<Array<main.ChatSession>>;

export function GetSkills():Promise<Array<main.Skill>>;

export function InstallSkill(arg1:string):Promise<string>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function Onboard(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SendMessage(arg1:string,arg2:Array<string>):Promise<main.ChatSession>;

export function SetCurrentSession(arg1:string):Promise<void>;
